#!/bin/bash
# Script to compare package lists, pkg-config packages, and env vars generated by compare_packages.sh
# Can compare individual files or auto-detect related files by base name

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

print_header() {
    echo -e "${CYAN}=== $1 ===${NC}"
}

print_info() {
    echo -e "${GREEN}INFO:${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}WARNING:${NC} $1"
}

print_error() {
    echo -e "${RED}ERROR:${NC} $1"
}

if [[ $# -lt 2 ]]; then
    print_error "Usage: $0 <base_name_1> <base_name_2>"
    echo ""
    echo "The script will automatically find related files:"
    echo "  - *.all (package names)"
    echo "  - *.dpkg_full (full dpkg output)"
    echo "  - *.pkgconfig_all (all pkg-config packages)"
    echo "  - *.env_all (all environment variables)"
    echo ""
    echo "Example:"
    echo "  $0 package_lists/package_list_localvm_22.04_20240101_120000 package_lists/package_list_github_22.04_20240101_120000"
    echo ""
    echo "Or specify individual files:"
    echo "  $0 -f package_lists/file1.all package_lists/file2.all"
    exit 1
fi

# Check if -f flag is used for individual file comparison
COMPARE_INDIVIDUAL=false
if [[ "$1" == "-f" ]]; then
    COMPARE_INDIVIDUAL=true
    shift
fi

if [[ $COMPARE_INDIVIDUAL == true ]]; then
    FILE1="$1"
    FILE2="$2"
    
    if [[ ! -f "$FILE1" ]]; then
        print_error "File not found: $FILE1"
        exit 1
    fi
    
    if [[ ! -f "$FILE2" ]]; then
        print_error "File not found: $FILE2"
        exit 1
    fi
    
    # Extract base name for finding related files
    BASE1=$(echo "$FILE1" | sed 's/\.[^.]*$//')
    BASE2=$(echo "$FILE2" | sed 's/\.[^.]*$//')
else
    BASE1="$1"
    BASE2="$2"
    
    # Find the actual files
    FILE1_ALL=$(find package_lists -name "$(basename "$BASE1").all" 2>/dev/null | head -1)
    FILE2_ALL=$(find package_lists -name "$(basename "$BASE2").all" 2>/dev/null | head -1)
    
    if [[ -z "$FILE1_ALL" ]] || [[ -z "$FILE2_ALL" ]]; then
        print_error "Could not find package list files"
        print_info "Looking for: $(basename "$BASE1").all and $(basename "$BASE2").all"
        exit 1
    fi
    
    BASE1=$(echo "$FILE1_ALL" | sed 's/\.all$//')
    BASE2=$(echo "$FILE2_ALL" | sed 's/\.all$//')
fi

FILE1="${BASE1}.all"
FILE2="${BASE2}.all"
FILE1_DPKG="${BASE1}.dpkg_full"
FILE2_DPKG="${BASE2}.dpkg_full"
FILE1_PKGCFG="${BASE1}.pkgconfig_all"
FILE2_PKGCFG="${BASE2}.pkgconfig_all"
FILE1_ENV="${BASE1}.env_all"
FILE2_ENV="${BASE2}.env_all"

if [[ ! -f "$FILE1" ]]; then
    print_error "File not found: $FILE1"
    exit 1
fi

if [[ ! -f "$FILE2" ]]; then
    print_error "File not found: $FILE2"
    exit 1
fi

print_header "Package List Comparison"
echo ""
print_info "File 1: $FILE1"
print_info "File 2: $FILE2"
echo ""

# Find packages only in file 1
print_header "Packages only in File 1 (not in File 2)"
comm -23 <(sort "$FILE1") <(sort "$FILE2") | head -20
TOTAL_ONLY_IN_1=$(comm -23 <(sort "$FILE1") <(sort "$FILE2") | wc -l)
echo ""
print_info "Total: $TOTAL_ONLY_IN_1 packages"
echo ""

# Find packages only in file 2
print_header "Packages only in File 2 (not in File 1)"
comm -13 <(sort "$FILE1") <(sort "$FILE2") | head -20
TOTAL_ONLY_IN_2=$(comm -13 <(sort "$FILE1") <(sort "$FILE2") | wc -l)
echo ""
print_info "Total: $TOTAL_ONLY_IN_2 packages"
echo ""

# Focus on ImageMagick-related packages
print_header "ImageMagick-related packages difference"
IMAGEMAGICK_PATTERNS=(
    "liblcms"
    "liblqr"
    "libdjvulibre"
    "libopenexr"
    "libjbig"
    "libtiff"
    "libopenjp2"
    "imagemagick"
    "libmagick"
    "libheif"
    "libde265"
    "libturbojpeg"
)

echo ""
print_info "Packages in File 1 but not File 2:"
for pattern in "${IMAGEMAGICK_PATTERNS[@]}"; do
    comm -23 <(sort "$FILE1") <(sort "$FILE2") | grep -i "$pattern" || true
done

echo ""
print_info "Packages in File 2 but not File 1:"
for pattern in "${IMAGEMAGICK_PATTERNS[@]}"; do
    comm -13 <(sort "$FILE1") <(sort "$FILE2") | grep -i "$pattern" || true
done

# Check for -dev packages
print_header "Development packages difference"
echo ""
print_info "Dev packages only in File 1:"
comm -23 <(sort "$FILE1") <(sort "$FILE2") | grep '\-dev' | head -20

echo ""
print_info "Dev packages only in File 2:"
comm -13 <(sort "$FILE1") <(sort "$FILE2") | grep '\-dev' | head -20

# Compare pkg-config packages if files exist
if [[ -f "$FILE1_PKGCFG" ]] && [[ -f "$FILE2_PKGCFG" ]]; then
    print_header "pkg-config Packages Comparison"
    echo ""
    print_info "pkg-config packages only in File 1:"
    comm -23 <(sort "$FILE1_PKGCFG") <(sort "$FILE2_PKGCFG") | head -20
    TOTAL_PKGCFG_ONLY_1=$(comm -23 <(sort "$FILE1_PKGCFG") <(sort "$FILE2_PKGCFG") | wc -l)
    
    echo ""
    print_info "pkg-config packages only in File 2:"
    comm -13 <(sort "$FILE1_PKGCFG") <(sort "$FILE2_PKGCFG") | head -20
    TOTAL_PKGCFG_ONLY_2=$(comm -13 <(sort "$FILE1_PKGCFG") <(sort "$FILE2_PKGCFG") | wc -l)
    
    echo ""
    print_info "Total pkg-config packages in File 1: $(wc -l < "$FILE1_PKGCFG")"
    print_info "Total pkg-config packages in File 2: $(wc -l < "$FILE2_PKGCFG")"
    print_info "pkg-config packages only in File 1: $TOTAL_PKGCFG_ONLY_1"
    print_info "pkg-config packages only in File 2: $TOTAL_PKGCFG_ONLY_2"
    echo ""
    
    # Check for ImageMagick-related pkg-config packages
    print_info "ImageMagick-related pkg-config packages in differences:"
    for pattern in "${IMAGEMAGICK_PATTERNS[@]}"; do
        comm -23 <(sort "$FILE1_PKGCFG") <(sort "$FILE2_PKGCFG") | grep -i "$pattern" || true
        comm -13 <(sort "$FILE1_PKGCFG") <(sort "$FILE2_PKGCFG") | grep -i "$pattern" || true
    done
else
    print_warning "pkg-config package files not found, skipping comparison"
fi

# Compare environment variables if files exist
if [[ -f "$FILE1_ENV" ]] && [[ -f "$FILE2_ENV" ]]; then
    print_header "Environment Variables Comparison"
    echo ""
    print_info "Environment variables only in File 1:"
    comm -23 <(sort "$FILE1_ENV") <(sort "$FILE2_ENV") | head -20
    TOTAL_ENV_ONLY_1=$(comm -23 <(sort "$FILE1_ENV") <(sort "$FILE2_ENV") | wc -l)
    
    echo ""
    print_info "Environment variables only in File 2:"
    comm -13 <(sort "$FILE1_ENV") <(sort "$FILE2_ENV") | head -20
    TOTAL_ENV_ONLY_2=$(comm -13 <(sort "$FILE1_ENV") <(sort "$FILE2_ENV") | wc -l)
    
    echo ""
    print_info "Total env vars in File 1: $(wc -l < "$FILE1_ENV")"
    print_info "Total env vars in File 2: $(wc -l < "$FILE2_ENV")"
    print_info "Env vars only in File 1: $TOTAL_ENV_ONLY_1"
    print_info "Env vars only in File 2: $TOTAL_ENV_ONLY_2"
    echo ""
    
    # Show differences in important env vars
    print_info "Important environment variable differences:"
    IMPORTANT_VARS=("PATH" "PKG_CONFIG_PATH" "LD_LIBRARY_PATH" "CC" "CXX")
    for var in "${IMPORTANT_VARS[@]}"; do
        val1=$(grep "^${var}=" "$FILE1_ENV" | cut -d'=' -f2- || echo "(not set)")
        val2=$(grep "^${var}=" "$FILE2_ENV" | cut -d'=' -f2- || echo "(not set)")
        if [[ "$val1" != "$val2" ]]; then
            echo "  ${var}:"
            echo "    File 1: $val1"
            echo "    File 2: $val2"
        fi
    done
else
    print_warning "Environment variable files not found, skipping comparison"
fi

# Compare full dpkg output if files exist
if [[ -f "$FILE1_DPKG" ]] && [[ -f "$FILE2_DPKG" ]]; then
    print_header "Full dpkg Output Comparison"
    echo ""
    print_info "Full dpkg comparison (showing first 30 differences):"
    diff "$FILE1_DPKG" "$FILE2_DPKG" | head -30 || true
    echo ""
    print_info "Use 'diff $FILE1_DPKG $FILE2_DPKG' for full comparison"
fi

print_header "Summary"
echo ""
print_info "Package comparison:"
print_info "  Total packages in File 1: $(wc -l < "$FILE1")"
print_info "  Total packages in File 2: $(wc -l < "$FILE2")"
print_info "  Packages only in File 1: $TOTAL_ONLY_IN_1"
print_info "  Packages only in File 2: $TOTAL_ONLY_IN_2"

if [[ -f "$FILE1_PKGCFG" ]] && [[ -f "$FILE2_PKGCFG" ]]; then
    print_info ""
    print_info "pkg-config comparison:"
    print_info "  pkg-config packages only in File 1: $TOTAL_PKGCFG_ONLY_1"
    print_info "  pkg-config packages only in File 2: $TOTAL_PKGCFG_ONLY_2"
fi

if [[ -f "$FILE1_ENV" ]] && [[ -f "$FILE2_ENV" ]]; then
    print_info ""
    print_info "Environment variables comparison:"
    print_info "  Env vars only in File 1: $TOTAL_ENV_ONLY_1"
    print_info "  Env vars only in File 2: $TOTAL_ENV_ONLY_2"
fi

echo ""
print_warning "Look for ImageMagick-related packages in the differences above"
print_warning "These are likely causing configure to auto-detect optional libraries"

